; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = balcony-installed

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = COM5  ; replace with real COM port
monitor_port = COM5
monitor_filters = time, esp32_exception_decoder

[env:balcony-installed]
extends = env:esp32doit-devkit-v1
build_flags =
  -DMBG_DEVICE_ID=\"550e8400-e29b-41d4-a716-446655440000\"

[env:bench-prototype]
extends = env:esp32doit-devkit-v1
build_flags =
  -DMBG_DEVICE_ID=\"318fab98-89ad-4f36-9100-3134a04e0be5\"
