#ifndef PROFILE_OVERRIDES_H
#define PROFILE_OVERRIDES_H

#ifdef MBG_RELAY_PIN
#undef RELAY_PIN
#define RELAY_PIN MBG_RELAY_PIN
#endif

#ifdef MBG_DHT_PIN
#undef DHTPIN
#define DHTPIN MBG_DHT_PIN
#endif

#ifdef MBG_SOIL_PIN
#undef SOIL_PIN
#define SOIL_PIN MBG_SOIL_PIN
#endif

#ifndef MBG_PUMP_CONTROL_AVAILABLE
#define MBG_PUMP_CONTROL_AVAILABLE 0
#endif

#ifndef MBG_DEVICE_CAN_WATER
#define MBG_DEVICE_CAN_WATER 0
#endif

#ifndef MBG_WATERING_SIMULATION_AVAILABLE
#define MBG_WATERING_SIMULATION_AVAILABLE 0
#endif

#if MBG_PUMP_CONTROL_AVAILABLE && !defined(RELAY_PIN)
#error "MBG_PUMP_CONTROL_AVAILABLE requires RELAY_PIN"
#endif

#ifdef MBG_GEN2_ENABLED
#ifndef MBG_HAS_DHT11
#define MBG_HAS_DHT11 0
#endif

#ifndef MBG_HAS_BME280
#define MBG_HAS_BME280 0
#endif

#ifndef MBG_HAS_DS18B20
#define MBG_HAS_DS18B20 0
#endif

#ifndef MBG_HAS_VEML6030
#define MBG_HAS_VEML6030 0
#endif

#ifndef MBG_HAS_SOIL_MOISTURE
#define MBG_HAS_SOIL_MOISTURE 0
#endif

#ifndef MBG_GEN2_ENABLE_LEGACY_LOGS
#define MBG_GEN2_ENABLE_LEGACY_LOGS 0
#endif

#define MBG_HAS_I2C_MODULES (MBG_HAS_BME280 || MBG_HAS_VEML6030)

#ifndef MBG_I2C_SDA_PIN
#define MBG_I2C_SDA_PIN 21
#endif

#ifndef MBG_I2C_SCL_PIN
#define MBG_I2C_SCL_PIN 22
#endif

#if MBG_HAS_DS18B20 && !defined(MBG_DS18B20_PIN)
#error "MBG_HAS_DS18B20 requires MBG_DS18B20_PIN"
#endif

#if MBG_HAS_DHT11 && MBG_HAS_I2C_MODULES && ((DHTPIN == MBG_I2C_SDA_PIN) || (DHTPIN == MBG_I2C_SCL_PIN))
#error "Gen2 DHT11 pin conflicts with configured I2C pins"
#endif

#if MBG_DEVICE_CAN_WATER && !MBG_PUMP_CONTROL_AVAILABLE
#error "MBG_DEVICE_CAN_WATER requires MBG_PUMP_CONTROL_AVAILABLE"
#endif

#if MBG_DEVICE_CAN_WATER && !MBG_HAS_SOIL_MOISTURE
#error "MBG_DEVICE_CAN_WATER requires MBG_HAS_SOIL_MOISTURE"
#endif

#endif

#endif
